name: agri_guide
description: Agri Guide - A Smart Innovative Platform for Crop Prediction

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.1+43

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_clean_architecture: ^3.1.0
  fluttertoast: ^7.1.8
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  get_it: ^6.0.0
  firebase_core: ^1.0.1
  http: ^0.13.1
  url_launcher: ^6.0.2
  email_validator: ^2.0.1
  checkdigit: ^0.2.0
  syncfusion_flutter_charts: ^18.4.39
  path_provider: ^2.0.1
  multi_select_flutter: ^3.1.8
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 500
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf
        - asset: fonts/Oxygen-Bold.ttf
          weight: 700
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

  assets:
    - assets/icon.png
    - assets/splash_v1.png
    - assets/splash_web.png
    - assets/no_filter_selected.png
    - assets/app_bar_bg.png
    - assets/select_state.png
    - assets/select_district.png
    - assets/login_to_continue.png
    - assets/login_heading1.png
    - assets/register_heading.png

