name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
   
  static_analysis:
    name: Static Analysis & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
      
      - name: Get Dependencies 
        run: flutter pub get

      - name: Run Static Analysis
        run: flutter analyze
      
      - name: Run Flutter Tests
        run: flutter test