name: Purge old artifacts

on:
  schedule:
    # Every Sunday at 12am
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Purge old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'